import * as dotenv from "dotenv";
import { defineConfig } from "drizzle-kit";

dotenv.config({ path: ".env.local" });
if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not defined in .env.local");
}

export default defineConfig({
  schema: ".lib/db/schema.ts",
  out: "./drizzle", //SQL queries will be generated by drizzle in this folder
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
  migrations: {
    table: "__drizzle_migrations", //table name for migrations
    schema: "public", //schema name for migrations
  },
  verbose: true, //show SQL queries in the console
  strict: true, //strict mode for TypeScript
});
